-- Generated by scripts/gen-tracks-seed.mjs — do not edit by hand.
begin;

insert into public.tracks (slug, title, subtitle, description, icon, color, difficulty, status, sort_order)
values ('frontend', 'Frontend Developer', 'HTML, CSS, JavaScript → React & TypeScript', 'Become a job-ready frontend engineer: semantic HTML, modern CSS, JavaScript, TypeScript, React, tooling, testing, and performance.', '🎨', '#0ea5e9', 'Beginner → Advanced', 'published', 1)
on conflict (slug) do update set title=excluded.title, subtitle=excluded.subtitle,
  description=excluded.description, icon=excluded.icon, color=excluded.color,
  difficulty=excluded.difficulty, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='frontend'), 'internet-web', 'How the Web Works', 'Understand the browser, HTTP, and how pages are delivered.', 0)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='internet-web'), 'how-web-works', 'How the internet & browsers work', 'Clients, servers, DNS, the request/response cycle, and how a browser renders a page.', 2, '[{"kind":"article","title":"MDN: How the web works","url":"https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works"},{"kind":"article","title":"MDN: What is HTTP","url":"https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='internet-web'), 'dev-setup', 'Editor, terminal & Git basics', 'Set up VS Code, the command line, and Git/GitHub for version control.', 3, '[{"kind":"doc","title":"Git documentation","url":"https://git-scm.com/doc"},{"kind":"course","title":"freeCodeCamp: Git & GitHub","url":"https://www.freecodecamp.org/news/git-and-github-for-beginners/"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='frontend'), 'html-css', 'HTML & CSS', 'Build accessible, responsive page structure and styling.', 1)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='html-css'), 'semantic-html', 'Semantic HTML & forms', 'Document structure, semantic elements, forms, and accessibility basics.', 4, '[{"kind":"doc","title":"MDN: HTML","url":"https://developer.mozilla.org/en-US/docs/Web/HTML"},{"kind":"article","title":"MDN: HTML forms","url":"https://developer.mozilla.org/en-US/docs/Learn/Forms"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='html-css'), 'css-fundamentals', 'CSS fundamentals & the box model', 'Selectors, specificity, the box model, units, and colors.', 4, '[{"kind":"doc","title":"MDN: CSS","url":"https://developer.mozilla.org/en-US/docs/Web/CSS"},{"kind":"course","title":"web.dev: Learn CSS","url":"https://web.dev/learn/css"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='html-css'), 'flexbox-grid', 'Flexbox & Grid layout', 'Modern layout with Flexbox and CSS Grid; responsive design with media queries.', 5, '[{"kind":"article","title":"CSS-Tricks: A Guide to Flexbox","url":"https://css-tricks.com/snippets/css/a-guide-to-flexbox/"},{"kind":"article","title":"CSS-Tricks: A Guide to Grid","url":"https://css-tricks.com/snippets/css/complete-guide-grid/"}]'::jsonb, 'published', 2)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='html-css'), 'responsive', 'Responsive & accessible design', 'Mobile-first design, media queries, and accessibility (a11y) fundamentals.', 4, '[{"kind":"course","title":"web.dev: Learn Responsive Design","url":"https://web.dev/learn/design"},{"kind":"doc","title":"MDN: Accessibility","url":"https://developer.mozilla.org/en-US/docs/Web/Accessibility"}]'::jsonb, 'published', 3)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='frontend'), 'javascript', 'JavaScript', 'Master the language that powers the web.', 2)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='javascript'), 'js-basics', 'JS fundamentals', 'Variables, types, operators, control flow, and functions.', 6, '[{"kind":"course","title":"javascript.info: The Modern JavaScript Tutorial","url":"https://javascript.info/"},{"kind":"doc","title":"MDN: JavaScript Guide","url":"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='javascript'), 'dom', 'The DOM & events', 'Select and manipulate elements, handle events, and update the page.', 4, '[{"kind":"doc","title":"MDN: Document Object Model","url":"https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model"},{"kind":"article","title":"MDN: Introduction to events","url":"https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='javascript'), 'async-js', 'Async JS, promises & fetch', 'Callbacks, promises, async/await, and calling APIs with fetch.', 5, '[{"kind":"article","title":"MDN: Asynchronous JavaScript","url":"https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous"},{"kind":"doc","title":"MDN: Using the Fetch API","url":"https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch"}]'::jsonb, 'published', 2)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='javascript'), 'es-modules', 'Modules, tooling & npm', 'ES modules, package management with npm, and bundling with Vite.', 3, '[{"kind":"doc","title":"MDN: JavaScript modules","url":"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules"},{"kind":"doc","title":"Vite Guide","url":"https://vitejs.dev/guide/"}]'::jsonb, 'published', 3)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='frontend'), 'typescript', 'TypeScript', 'Add static types for safer, larger apps.', 3)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='typescript'), 'ts-basics', 'TypeScript fundamentals', 'Types, interfaces, generics, and typing functions and objects.', 5, '[{"kind":"doc","title":"TypeScript Handbook","url":"https://www.typescriptlang.org/docs/handbook/intro.html"},{"kind":"practice","title":"TypeScript Playground","url":"https://www.typescriptlang.org/play"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='frontend'), 'react', 'React', 'Build component-based UIs with React and TypeScript.', 4)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='react'), 'react-basics', 'Components, JSX & props', 'Thinking in components, JSX, props, and rendering lists.', 5, '[{"kind":"doc","title":"react.dev: Learn React","url":"https://react.dev/learn"},{"kind":"doc","title":"react.dev: Describing the UI","url":"https://react.dev/learn/describing-the-ui"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='react'), 'react-state', 'State & hooks', 'useState, useEffect, controlled inputs, and the rules of hooks.', 6, '[{"kind":"doc","title":"react.dev: State","url":"https://react.dev/learn/state-a-components-memory"},{"kind":"doc","title":"react.dev: Reference for Hooks","url":"https://react.dev/reference/react/hooks"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='react'), 'react-data', 'Data fetching & routing', 'Fetch data, manage loading/error states, and add client-side routing.', 5, '[{"kind":"doc","title":"react.dev: Synchronizing with Effects","url":"https://react.dev/learn/synchronizing-with-effects"},{"kind":"doc","title":"React Router","url":"https://reactrouter.com/en/main/start/tutorial"}]'::jsonb, 'published', 2)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='frontend' and mo.slug='react'), 'react-testing', 'Testing & performance', 'Test components with Testing Library and optimize render performance.', 4, '[{"kind":"doc","title":"Testing Library docs","url":"https://testing-library.com/docs/"},{"kind":"doc","title":"react.dev: Render and Commit","url":"https://react.dev/learn/render-and-commit"}]'::jsonb, 'published', 3)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.tracks (slug, title, subtitle, description, icon, color, difficulty, status, sort_order)
values ('backend', 'Backend Developer', 'APIs, databases, auth, caching & queues', 'Design and build production backends: HTTP & REST, Node.js/Express, SQL with PostgreSQL, authentication, caching with Redis, and containerized deploys.', '🛠️', '#22c55e', 'Beginner → Advanced', 'published', 2)
on conflict (slug) do update set title=excluded.title, subtitle=excluded.subtitle,
  description=excluded.description, icon=excluded.icon, color=excluded.color,
  difficulty=excluded.difficulty, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='backend'), 'foundations', 'Backend Foundations', 'Understand HTTP, REST, and how servers work.', 0)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='foundations'), 'http-rest', 'HTTP & REST fundamentals', 'HTTP methods, status codes, headers, and RESTful API design.', 3, '[{"kind":"doc","title":"MDN: HTTP","url":"https://developer.mozilla.org/en-US/docs/Web/HTTP"},{"kind":"article","title":"MDN: REST glossary","url":"https://developer.mozilla.org/en-US/docs/Glossary/REST"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='foundations'), 'cli-git', 'Command line & Git', 'Work confidently in the terminal and version code with Git.', 3, '[{"kind":"doc","title":"Git documentation","url":"https://git-scm.com/doc"},{"kind":"doc","title":"Ubuntu: The Linux command line","url":"https://ubuntu.com/tutorials/command-line-for-beginners"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='backend'), 'node-express', 'Node.js & Express', 'Build HTTP APIs with Node.js and Express.', 1)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='node-express'), 'node-basics', 'Node.js fundamentals', 'The event loop, modules, npm, and the standard library.', 5, '[{"kind":"doc","title":"Node.js: Learn","url":"https://nodejs.org/en/learn/getting-started/introduction-to-nodejs"},{"kind":"doc","title":"Node.js API docs","url":"https://nodejs.org/docs/latest/api/"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='node-express'), 'express-api', 'Building REST APIs with Express', 'Routing, middleware, request/response handling, and error handling.', 6, '[{"kind":"doc","title":"Express: Getting started","url":"https://expressjs.com/en/starter/installing.html"},{"kind":"doc","title":"Express: Routing","url":"https://expressjs.com/en/guide/routing.html"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='node-express'), 'validation', 'Validation & error handling', 'Validate input, structure errors, and return correct status codes.', 3, '[{"kind":"doc","title":"Express: Error handling","url":"https://expressjs.com/en/guide/error-handling.html"},{"kind":"doc","title":"Zod (schema validation)","url":"https://zod.dev/"}]'::jsonb, 'published', 2)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='backend'), 'databases', 'Databases & SQL', 'Model data and query it with PostgreSQL.', 2)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='databases'), 'sql-basics', 'SQL & relational modeling', 'Tables, keys, joins, constraints, and normalization.', 6, '[{"kind":"doc","title":"PostgreSQL Tutorial","url":"https://www.postgresqltutorial.com/"},{"kind":"doc","title":"PostgreSQL documentation","url":"https://www.postgresql.org/docs/current/"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='databases'), 'indexes-tx', 'Indexes & transactions', 'Speed up queries with indexes; group operations with transactions.', 4, '[{"kind":"doc","title":"PostgreSQL: Indexes","url":"https://www.postgresql.org/docs/current/indexes.html"},{"kind":"doc","title":"PostgreSQL: Transactions","url":"https://www.postgresql.org/docs/current/tutorial-transactions.html"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='databases'), 'orm', 'ORMs & migrations', 'Query from code with an ORM and version your schema with migrations.', 4, '[{"kind":"doc","title":"Prisma: Getting started","url":"https://www.prisma.io/docs/getting-started"},{"kind":"doc","title":"node-postgres (pg)","url":"https://node-postgres.com/"}]'::jsonb, 'published', 2)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='backend'), 'auth-security', 'Auth & Security', 'Authenticate users and secure your API.', 3)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='auth-security'), 'auth', 'Authentication & JWT', 'Password hashing, sessions vs tokens, and JSON Web Tokens.', 5, '[{"kind":"article","title":"JWT: Introduction","url":"https://jwt.io/introduction"},{"kind":"doc","title":"OWASP: Authentication Cheat Sheet","url":"https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='auth-security'), 'security', 'API security basics', 'Common vulnerabilities and how to defend against them.', 3, '[{"kind":"doc","title":"OWASP Top 10","url":"https://owasp.org/www-project-top-ten/"},{"kind":"doc","title":"MDN: Web security","url":"https://developer.mozilla.org/en-US/docs/Web/Security"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='backend'), 'scaling-deploy', 'Caching, Queues & Deploy', 'Make the backend fast and shippable.', 4)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='scaling-deploy'), 'redis', 'Caching with Redis', 'Cache expensive results, use TTLs, and rate-limit requests.', 4, '[{"kind":"doc","title":"Redis documentation","url":"https://redis.io/docs/latest/"},{"kind":"doc","title":"Redis: Data types","url":"https://redis.io/docs/latest/develop/data-types/"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='backend' and mo.slug='scaling-deploy'), 'docker-deploy', 'Containerize & deploy', 'Package the app with Docker and deploy it.', 5, '[{"kind":"doc","title":"Docker: Get started","url":"https://docs.docker.com/get-started/"},{"kind":"doc","title":"12-Factor App","url":"https://12factor.net/"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.tracks (slug, title, subtitle, description, icon, color, difficulty, status, sort_order)
values ('devops', 'DevOps Engineer', 'Linux, Docker, Kubernetes, CI/CD & cloud', 'Operate and ship software reliably: Linux and networking, Docker, Kubernetes, infrastructure as code, CI/CD pipelines, and observability.', '⚙️', '#f59e0b', 'Intermediate → Advanced', 'published', 3)
on conflict (slug) do update set title=excluded.title, subtitle=excluded.subtitle,
  description=excluded.description, icon=excluded.icon, color=excluded.color,
  difficulty=excluded.difficulty, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='devops'), 'linux-net', 'Linux & Networking', 'Be fluent on the command line and understand networking.', 0)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='linux-net'), 'linux', 'Linux command line', 'Filesystem, permissions, processes, and shell scripting.', 5, '[{"kind":"course","title":"Linux Journey","url":"https://linuxjourney.com/"},{"kind":"doc","title":"Ubuntu: Command line for beginners","url":"https://ubuntu.com/tutorials/command-line-for-beginners"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='linux-net'), 'networking', 'Networking basics', 'IP, DNS, TCP/HTTP, ports, and load balancing.', 3, '[{"kind":"article","title":"Cloudflare: What is DNS?","url":"https://www.cloudflare.com/learning/dns/what-is-dns/"},{"kind":"doc","title":"MDN: HTTP","url":"https://developer.mozilla.org/en-US/docs/Web/HTTP"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='devops'), 'version-scm', 'Git & Automation', 'Version control and scripting for automation.', 1)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='version-scm'), 'git', 'Git & GitHub workflows', 'Branching, pull requests, and collaboration workflows.', 3, '[{"kind":"doc","title":"Git documentation","url":"https://git-scm.com/doc"},{"kind":"doc","title":"GitHub: Git guides","url":"https://github.com/git-guides"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='version-scm'), 'bash', 'Bash scripting', 'Automate repetitive tasks with shell scripts.', 3, '[{"kind":"doc","title":"GNU Bash manual","url":"https://www.gnu.org/software/bash/manual/bash.html"},{"kind":"article","title":"Bash scripting cheatsheet","url":"https://devhints.io/bash"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='devops'), 'containers', 'Containers', 'Package and run apps with Docker.', 2)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='containers'), 'docker', 'Docker fundamentals', 'Images, containers, Dockerfiles, volumes, and networking.', 5, '[{"kind":"doc","title":"Docker: Get started","url":"https://docs.docker.com/get-started/"},{"kind":"doc","title":"Dockerfile reference","url":"https://docs.docker.com/reference/dockerfile/"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='containers'), 'compose', 'Docker Compose', 'Define and run multi-container apps for local development.', 3, '[{"kind":"doc","title":"Docker Compose overview","url":"https://docs.docker.com/compose/"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='devops'), 'orchestration', 'Kubernetes', 'Orchestrate containers at scale.', 3)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='orchestration'), 'k8s-basics', 'Kubernetes basics', 'Pods, Deployments, Services, and the control plane.', 6, '[{"kind":"doc","title":"Kubernetes basics tutorial","url":"https://kubernetes.io/docs/tutorials/kubernetes-basics/"},{"kind":"doc","title":"Kubernetes concepts","url":"https://kubernetes.io/docs/concepts/"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='orchestration'), 'k8s-config', 'Config, secrets & scaling', 'ConfigMaps, Secrets, health checks, and autoscaling.', 4, '[{"kind":"doc","title":"Kubernetes: ConfigMaps","url":"https://kubernetes.io/docs/concepts/configuration/configmap/"},{"kind":"doc","title":"Kubernetes: HPA","url":"https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='devops'), 'cicd-iac-obs', 'CI/CD, IaC & Observability', 'Automate delivery and observe production.', 4)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='cicd-iac-obs'), 'cicd', 'CI/CD with GitHub Actions', 'Build, test, and deploy automatically on every push.', 4, '[{"kind":"doc","title":"GitHub Actions documentation","url":"https://docs.github.com/en/actions"},{"kind":"doc","title":"GitHub Actions: Quickstart","url":"https://docs.github.com/en/actions/quickstart"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='cicd-iac-obs'), 'iac', 'Infrastructure as Code (Terraform)', 'Provision cloud infrastructure declaratively and reproducibly.', 5, '[{"kind":"doc","title":"Terraform tutorials","url":"https://developer.hashicorp.com/terraform/tutorials"},{"kind":"doc","title":"Terraform documentation","url":"https://developer.hashicorp.com/terraform/docs"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='devops' and mo.slug='cicd-iac-obs'), 'observability', 'Monitoring & observability', 'Metrics, logs, and traces with Prometheus and Grafana.', 4, '[{"kind":"doc","title":"Prometheus: Overview","url":"https://prometheus.io/docs/introduction/overview/"},{"kind":"doc","title":"Grafana documentation","url":"https://grafana.com/docs/grafana/latest/"}]'::jsonb, 'published', 2)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.tracks (slug, title, subtitle, description, icon, color, difficulty, status, sort_order)
values ('ai-engineer', 'AI Engineer', 'Python, LLMs, RAG & agents', 'Build AI-powered applications: Python foundations, working with LLMs and the Claude API, prompt engineering, retrieval-augmented generation, and agents.', '🤖', '#8b5cf6', 'Intermediate → Advanced', 'published', 4)
on conflict (slug) do update set title=excluded.title, subtitle=excluded.subtitle,
  description=excluded.description, icon=excluded.icon, color=excluded.color,
  difficulty=excluded.difficulty, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='ai-engineer'), 'python', 'Python for AI', 'Get fluent in Python and the data stack.', 0)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='python'), 'python-basics', 'Python fundamentals', 'Syntax, data structures, functions, and modules.', 6, '[{"kind":"doc","title":"Python: The Python Tutorial","url":"https://docs.python.org/3/tutorial/"},{"kind":"course","title":"Real Python: Learning path","url":"https://realpython.com/learning-paths/python-basics/"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='python'), 'numpy-pandas', 'NumPy & pandas', 'Vectorized arrays with NumPy and tabular data with pandas.', 5, '[{"kind":"doc","title":"NumPy: Absolute beginners","url":"https://numpy.org/doc/stable/user/absolute_beginners.html"},{"kind":"doc","title":"pandas: User guide","url":"https://pandas.pydata.org/docs/user_guide/index.html"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='ai-engineer'), 'llm-foundations', 'LLM Foundations', 'Understand LLMs and call them via the Claude API.', 1)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='llm-foundations'), 'what-are-llms', 'How LLMs work', 'Tokens, context windows, and what models can and cannot do.', 3, '[{"kind":"doc","title":"Anthropic: Intro to Claude","url":"https://docs.claude.com/en/docs/intro-to-claude"},{"kind":"article","title":"Anthropic: Models overview","url":"https://docs.claude.com/en/docs/about-claude/models"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='llm-foundations'), 'claude-api', 'Calling the Claude API', 'The Messages API, roles, streaming, and parameters.', 4, '[{"kind":"doc","title":"Claude API: Get started","url":"https://docs.claude.com/en/docs/get-started"},{"kind":"doc","title":"Claude API: Messages","url":"https://docs.claude.com/en/api/messages"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='ai-engineer'), 'prompting', 'Prompt Engineering', 'Get reliable results from LLMs.', 2)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='prompting'), 'prompt-basics', 'Prompt engineering', 'Clear instructions, examples, system prompts, and chain-of-thought.', 4, '[{"kind":"doc","title":"Anthropic: Prompt engineering overview","url":"https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/overview"},{"kind":"practice","title":"Anthropic prompting tutorial","url":"https://github.com/anthropics/prompt-eng-interactive-tutorial"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='prompting'), 'structured-tools', 'Structured output & tool use', 'Force JSON output and let the model call your tools.', 4, '[{"kind":"doc","title":"Claude API: Tool use","url":"https://docs.claude.com/en/docs/build-with-claude/tool-use"},{"kind":"doc","title":"Claude API: Streaming","url":"https://docs.claude.com/en/docs/build-with-claude/streaming"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='ai-engineer'), 'rag', 'RAG & Vector Search', 'Ground LLMs in your own documents.', 3)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='rag'), 'embeddings', 'Embeddings & vector search', 'Represent meaning as vectors and search by similarity.', 4, '[{"kind":"doc","title":"pgvector","url":"https://github.com/pgvector/pgvector"},{"kind":"article","title":"Anthropic: Embeddings","url":"https://docs.claude.com/en/docs/build-with-claude/embeddings"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='rag'), 'rag-pipeline', 'Building a RAG pipeline', 'Chunk, embed, retrieve, and generate grounded answers with citations.', 6, '[{"kind":"doc","title":"Anthropic: RAG guide","url":"https://docs.claude.com/en/docs/build-with-claude/search-and-retrieval"},{"kind":"doc","title":"FastAPI","url":"https://fastapi.tiangolo.com/"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

insert into public.modules (track_id, slug, title, goal, sort_order)
values ((select id from public.tracks where slug='ai-engineer'), 'agents', 'Agents', 'Build multi-step, tool-using agents.', 4)
on conflict (track_id, slug) do update set title=excluded.title, goal=excluded.goal, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='agents'), 'agent-basics', 'Agent loops & tools', 'The reason-act-observe loop, tool schemas, and stopping conditions.', 5, '[{"kind":"doc","title":"Anthropic: Building effective agents","url":"https://www.anthropic.com/research/building-effective-agents"},{"kind":"doc","title":"LangGraph","url":"https://langchain-ai.github.io/langgraph/"}]'::jsonb, 'published', 0)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;
insert into public.topics (module_id, slug, title, description, est_hours, resources, status, sort_order)
values ((select mo.id from public.modules mo join public.tracks tr on tr.id=mo.track_id where tr.slug='ai-engineer' and mo.slug='agents'), 'agent-eval', 'Evaluating & shipping agents', 'Guardrails, cost control, evaluation, and deployment.', 4, '[{"kind":"doc","title":"Anthropic: Reduce hallucinations","url":"https://docs.claude.com/en/docs/test-and-evaluate/strengthen-guardrails/reduce-hallucinations"},{"kind":"doc","title":"Anthropic: Define success criteria","url":"https://docs.claude.com/en/docs/test-and-evaluate/define-success"}]'::jsonb, 'published', 1)
on conflict (module_id, slug) do update set title=excluded.title, description=excluded.description,
  est_hours=excluded.est_hours, resources=excluded.resources, status=excluded.status, sort_order=excluded.sort_order;

commit;
